[package]
name = "cpt"
description = "CPT main cli program"
include = ["src/**/*", "README.md"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
clap_complete = "4.5.2"
console = "0.15.8"
dialoguer = "0.11.0"
env_logger = "0.11.6"
etcetera = "0.8.0"
indoc = "2.0.5"
itertools = "0.13.0"
log = "0.4.22"
num_cpus = "1.16.0"
regex = "1.10.4"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
strum = { version = "0.26.3", features = ["derive"] }
tempfile = "3.10.1"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
toml = "0.8.19"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
assert_fs = "1.1.2"
mockall = "0.13.0"
predicates = "3.1.2"
pretty_assertions = "1.4.0"
test-case = "3.3.1"
