[package]
name = "cpt"
version = "0.1.0"
edition = "2021"
description = "Competitive Programming Tools"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
clap_complete = "4.5.2"
colog = "1.3.0"
console = "0.15.8"
dialoguer = "0.11.0"
dirs-next = "2.0.0"
include_dir = "0.7.4"
indoc = "2.0.5"
itertools = "0.13.0"
log = "0.4.22"
num_cpus = "1.16.0"
proc-macro2 = "1.0.86"
regex = "1.10.4"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
strum = { version = "0.26.3", features = ["derive"] }
tempfile = "3.10.1"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
toml = "0.8.19"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
assert_fs = "1.1.2"
mockall = "0.13.0"
predicates = "3.1.2"
pretty_assertions = "1.4.0"
rstest = "0.22.0"
test-case = "3.3.1"
