[package]
name = "cp-tools"
version = "0.1.0"
edition = "2021"
description = "Competitive Programming Tools"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
clap_complete = "4.5.2"
colog = "1.3.0"
color-eyre = "0.6.3"
console = "0.15.8"
cookie_store = "0.21.0"
dialoguer = "0.11.0"
dirs-next = "2.0.0"
duct = "0.13.7"
itertools = "0.13.0"
log = "0.4.22"
proc_macros = "0.1.0"
regex = "1.10.4"
scraper = "0.19.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
similar = "2.5.0"
tempfile = "3.10.1"
thiserror = "1.0.62"
ureq = { version = "2.10.0", features = ["cookies"] }
url = "2.5.2"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
pretty_assertions = "1.4.0"
test-case = "3.3.1"

