[package]
name = "cpt"
version = "0.1.0"
edition = "2021"
description = "Competitive Programming Tools"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
clap_complete = "4.5.2"
colog = "1.3.0"
color-eyre = "0.6.3"
console = "0.15.8"
console-subscriber = "0.4.0"
dirs-next = "2.0.0"
itertools = "0.13.0"
log = "0.4.22"
num_cpus = "1.16.0"
regex = "1.10.4"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
tempfile = "3.10.1"
tokio = { version = "1.39.2", features = ["full"] }
url = "2.5.2"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
pretty_assertions = "1.4.0"
test-case = "3.3.1"

