[package]
name = "cp-tools"
version = "0.1.0"
edition = "2021"
description = "Competitive Programming Tools"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.2"
dirs-next = "2.0.0"
fern = { version = "0.6.2", features = ["colored"] }
log = "0.4.21"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["json", "cookies", "native-tls-alpn"] }
reqwest_cookie_store = { version = "0.7.0", features = ["serde"] }
rpassword = "7.3.1"
rprompt = "2.1.1"
scraper = "0.19.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["full"] }

