#--------------------------------------------------------------------------------
# Build/Run/Expand command definitions (fields with asterisk are mandatory).
#
# - *[name]
#   Language name
# - *[extensions]
#   Extension candidates for auto language detection.
#
# - [build]
#   Build command (input: ${src_path}, output: ${bin_path}).
#   - *[command]
#   - *[args]
#   -  [debug_args]
#   -  [release_args]
# 
# - [bundle]
#   Bundle command (input: ${src_path}, output: ${bundled_path})
#   - *[command]
#   - *[args]
#
#--------------------------------------------------------------------------------
# Available variables
#
# - ${src_path}
#   Source file path
#   (e.g.) `/home/sho/programming/main.cpp`
#
# - ${bin_path}
#   Executable file path
#   (e.g.) `/home/sho/programming/main.exe`
#
# - ${bundled_path}
#   Bundled file path
#   (e.g.) `/home/sho/programming/main_bundled.cpp`
#
# - ${tempdir}
#   Temporary directory path. Removed after command end) 
#   (e.g.) `/tmp/cpt-XXDSOI`
#
# Available constants
#
# - ${tool_workdir}
#   Workspace directory path for cp-tools
#   `/home/sho/.local/share/cpt/`
#
#--------------------------------------------------------------------------------
[[language]]
name = 'cpp'
extensions = ['cpp']
[language.build]
command = 'clang++'
args = ['-std=gnu++20', '-Wall', '-Wextra', '${src_path}', '-o', '${bin_path}']
debug_args = ['-g3', '-O0', '-fsanitize=undefined,address']
release_args = ['-O2']
[language.execute]
command = '${bin_path}'
args = []
# [[language.expand]]
# command = 'sh'
# args = [
#   '${tool_workdir}/cpp/create_dummy_headers.sh',
#   '/usr/include/c++/14.2.1',
#   '${tool_workdir}/cpp/dummy_headers',
# ]
# [[language.expand]]
# command = 'clang++'
# args = [
#   '-E',
#   '-P',
#   '-nostdinc',
#   '-nostdinc++',
#   '-I',
#   '/home/sho/ghq/github.com/pachicobue/algolib/src',
#   '-I',
#   '/home/sho/ghq/github.com/atcoder/ac-library',
#   '-I',
#   '${tool_workdir}/cpp/dummy_headers',
#   '${src_path}',
#   '-o',
#   '${tempdir}/pp.cpp',
# ]
# [[language.expand]]
# command = 'awk'
# args = [
#   '''
#   BEGIN { lines[NR]="" }
#   {
#     if ($0 ~ /#pragma INCLUDE/) {
#       print gensub(/#pragma INCLUDE<(.*)>/, "#include <\\1>", "g") > "${bundled_path}"
#     } else {
#       num = length(lines); lines[num] = $0
#     } 
#   }
#   END {
#     for (i = 0; i < length(lines); i++) {
#       print lines[i] > "${bundled_path}"
#     }
#   }
#   ''',
#   '${tempdir}/pp.cpp',
# ]
# [[language.expand]]
# command = 'clang-format'
# args = ['${bundled_path}', '-i']
