format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
edition = "2021"
version = "Two"
use_field_init_shorthand = true
condense_wildcard_suffixes = true
unstable_features = true
