name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: mkroening/rust-toolchain-toml@main
        
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Check format
        run: cargo fmt --all -- --check
        
      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings
        
      - name: Run tests
        run: cargo test --workspace
        
      - name: Install cargo-deny
        run: cargo install --locked cargo-deny
        
      - name: Run cargo deny
        run: cargo deny --all-features check
        
      - name: Install cargo-machete
        run: cargo install --locked cargo-machete
        
      - name: Run cargo machete
        run: cargo machete
        
      - name: Install cargo-about
        run: cargo install --locked cargo-about
        
      - name: Check cargo about diff
        run: |
          cargo about generate about.hbs > CREDIT_new.html
          diff CREDIT.html CREDIT_new.html || (echo "CREDIT.html is out of date. Run 'cargo about generate about.hbs > CREDIT.html' to update." && exit 1)
